# Generated by Django 5.1.3 on 2024-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "user"), ("ADMIN", "admin")],
                default="user",
                max_length=20,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
